// This file is automatically generated by lib/generate-icon-manifest.mjs.
// SVGs should be added to icon/svgs. Run `npm run build-icons` to regenerate,
// or restart the server. If you edited an existing SVG in place, run
// `npm run build-icons:force` instead, since the name-based staleness check
// won't notice a same-named file changed.

const iconManifest = {
  'angle-double-left': '0 0 384 512',
  'angle-double-right': '0 0 384 512',
  'angle-down': '0 0 320 512',
  'angle-left': '0 0 192 512',
  'angle-right': '0 0 192 512',
  'angle-up': '0 0 320 512',
  close: '0 0 22 22',
  facebook: '0 0 24 24',
  linkedin: '0 0 24 24',
  rss: '0 0 448 512',
  twitter: '0 0 24 24',
} as const;

export type IconName = keyof typeof iconManifest;

export default iconManifest;
