#!/bin/bash

## Description: Set up project for headless Drupal
## Usage: setup-drupal
## Example: "ddev setup-drupal"

node lib/drupal/merge-package-json.js
npm install --package-lock-only
npm ci
if [ ! -f ./codgen.ts ]; then
  cp ./starterkits/drupal/codegen.ts ./codegen.ts
fi
cat ./starterkits/drupal/.env.drupal >> .env.local.example
pm2 restart frontend
pm2 restart storybook
