#!/bin/bash

## Description: Set up project for headless Drupal
## Usage: setup-drupal
## Example: "ddev setup-drupal"

node lib/merge-package-json.js
npm install --package-lock-only
npm ci
pm2 restart app
pm2 restart storybook
