#!/bin/bash

## Description: Set up project for headless WordPress
## Usage: setup-wp
## Example: "ddev setup-wp"

if [ -e ./codegen.ts ] || [ -d ./app/api ]; then
  echo "WordPress setup can only be run once."
  echo "If you need the starter files, copy them from the /starterkits directory."
  exit 0;
fi

node lib/wp/merge-package-json.js
npm install --package-lock-only
npm ci
cp ./starterkits/wp/codegen.ts ./
cat ./starterkits/wp/.env.wp >> .env.local.example
cp -r ./starterkits/wp/app/* ./app/
cp -r ./starterkits/wp/editor-styles ./
cp -r ./starterkits/wp/util/* ./util/
cp -r ./starterkits/wp/types/* ./types/

cp -r ./starterkits/wp/block-fragments.ts ./
cp -r ./starterkits/wp/faust.config.js ./
rm ./next.config.js
cp -r ./starterkits/wp/next.config.mjs ./
cp -r ./starterkits/wp/possibleTypes.json ./

pm2 restart frontend
pm2 restart storybook
