#!/bin/bash

## Description: Moves items from a headless WordPress setup back into the starterkit.
## Usage: unsetup-wp
## Example: "ddev unsetup-wp"

cp ./codegen.ts ./starterkits/wp/

rm -rf ./starterkits/wp/app
cp -r ./app ./starterkits/wp/

rm -rf ./starterkits/wp/util/wp
cp -r ./util/wp ./starterkits/wp/util/

rm -rf ./starterkits/wp/types
cp -r ./types ./starterkits/wp/

rm -rf ./starterkits/wp/editor-styles
cp -r ./editor-styles ./starterkits/wp/

cp ./block-fragments.ts ./starterkits/wp/

pm2 restart frontend
pm2 restart storybook
