hooks:
  post-start:
    # Detects to see if the node_modules folder exists
    - exec: 'sh -c "[ ! -d node_modules ] && npm ci || true"'
      service: web
    - exec-host: |
        if [ -z "$START_UP_SERVICE" ]; then
          ddev exec pm2 start --name next node_modules/.bin/next -- dev --webpack
          ddev exec pm2 start --name storybook node_modules/.bin/storybook -- dev --no-open -p 6006

          echo "Next time use one of these for faster startup:"
          echo "> ddev up nextjs"
          echo "> ddev up storybook"
        fi
