hooks:
  post-start:
    # Detects to see if the node_modules folder exists
    - exec: 'sh -c "[ ! -d node_modules ] && npm ci || return"'
      service: web
    - exec: pm2 start --name next npm -- run dev
      service: web
    - exec: pm2 start --name storybook npm -- run storybook -- --no-open
      service: web
