version: '3.6'
services:
  embed:
    container_name: ddev-${DDEV_SITENAME}-embed
    build:
      context: ./../svc-embed
      dockerfile: dev.Dockerfile
    volumes:
      - ./../svc-embed/src:/app/src
      - ./../svc-embed/webpack:/app/webpack
      - ".:/mnt/ddev_config"
    expose:
      - 8080
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=8079:8080
      - HTTPS_EXPOSE=8080:8080
      - CHOKIDAR_USEPOLLING=1
      - CHOKIDAR_INTERVAL=1000
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    networks: [default, ddev_default]
